# Site settings
title: New World Literacy
header-img: img/home-bg.png
email: gpianka1@gmail.com
copyright_name: NotoriousCottonball
description: > # this means to ignore newlines until "baseurl:"
  Creativity, Craft, && Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  NotoriousCottonball
learn_profile: NotoriousCottonball
email_username: gpianka1@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
